---
title: "Figure: My COVID life in Canada"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load the libraries
library(tidyverse)
library(readr)
library(here)
library(english)
library(stringr)
library(scales)
library(ggridges)
library(plotly)
library(patchwork)
library(haven)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=10}
set.seed(1)

cases <- read_csv("data/covid19-download-jan2022.csv") %>%
  filter(prname == "Canada") %>%
  dplyr::select(date, avgtotal_last7) %>%
  mutate(group = as.factor(case_when(date > "2021-06-14" & date < "2021-08-04" ~ 1))) %>%
  mutate(group1 = as.factor(case_when(date > "2021-01-01" & date < "2021-02-01" ~ 2)))
    
test <- cases %>%
  filter(!is.na(group))

test2 <- cases %>%
  filter(!is.na(group1))

ggplot(cases, aes(x=date)) +
  geom_line(aes(y = avgtotal_last7), color = "dark blue", size = 1) +
  theme_bw() +
  labs(title = " ", x = "Tempus fugit", y = "Canadian COVID stats") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        text = element_text(size = 12),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank()) +
  scale_x_date(date_labels = "%b %d, %y", date_breaks = "1 month") +
  geom_ribbon(data = test, aes(x = date, group = group, ymax = avgtotal_last7, ymin = 0), fill = "orange", alpha = 0.8) +
  geom_text(data=test[23, ], aes(y = avgtotal_last7), label = "FML \n was home", y = 4000, size = 4, color = "orange") +
  geom_text(data=cases[8, ], aes(y = avgtotal_last7), label = "START", y = 0, size = 4, color = "red") +
  geom_text(data=cases[685, ], aes(y = avgtotal_last7), label = "I'm losing my mind ", y = 15000, size = 5, angle = 90, color = "red", fontface = "bold") +
  geom_text(data=cases[165, ], aes(y = avgtotal_last7), label = "Ok, whatever", y = 3000, size = 4) +
  geom_ribbon(data = test2, aes(x = date, group = group, ymax = avgtotal_last7, ymin = 0), fill = "light blue", alpha = 0.8) +
  geom_text(data=test2[2, ], aes(y = avgtotal_last7), label = "2019 was \na month ago", y = 12000, size = 4, color = "blue") 
```
